MODULE_TOPDIR = ../..

PGM = r.level

LIBES = $(MATHLIB) $(GISLIB) $(RASTERLIB) $(SEGMENTLIB)
DEPENDENCIES = $(GISDEP) $(RASTERDEP) $(SEGMENTDEP)
EXTRA_CFLAGS = -fopenmp

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
